#!/bin/bash

client="root@<<RASPLEX IP>>"
netcontroller="pi@<<NETWORK CONTROLLER OR OTHER EXTRA PI IP>>"
controller="pi@<<CONTROLLER IP>>"
server="pi@<<SERVER IP>>"

ssh-keygen -t rsa
ssh-copy-id $client
ssh-copy-id $netcontroller
ssh-copy-id $controller
ssh-copy-id $server

exit 0
